version: '3.8'

# Note: This application now uses H2 in-memory database
# No external database service is required
# The H2 console is available at http://localhost:8080/h2-console
# JDBC URL: jdbc:h2:mem:testdb
# Username: sa
# Password: (empty)

