version: '3.8'

services:
  yugabytedb:
    image: yugabytedb/yugabyte:latest
    container_name: yugabyte-demo
    ports:
      - "7000:7000"   # Master web UI
      - "9000:9000"   # TServer web UI
      - "5433:5433"   # YSQL (PostgreSQL-compatible)
      - "9042:9042"   # YCQL (Cassandra-compatible)
    command: ["bin/yugabyted", "start", "--daemon=false"]
    environment:
      - YSQL_USER=yugabyte
      - YSQL_PASSWORD=yugabyte
      - YSQL_DB=yugabyte
    volumes:
      - yugabyte-data:/home/yugabyte/var
    healthcheck:
      test: ["CMD", "bin/yugabyted", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  yugabyte-data:
    driver: local

