-- Sample data with 100 unique products with variance
-- Categories: Electronics, Home & Kitchen, Sports, Books, Clothing, Toys, Office, Automotive, Beauty, Food

-- Electronics (Products 1-20)
INSERT INTO products (name, description, price, stock_quantity, last_updated, created_at) VALUES
('Gaming Laptop Pro', '17-inch display, RTX 4080, 32GB RAM, 2TB SSD, RGB keyboard', 2499.99, 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Wireless Noise-Cancelling Headphones', 'Premium audio quality with active noise cancellation and 40-hour battery', 349.99, 150, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('4K Smart TV 65"', 'OLED display, HDR10+, Dolby Atmos, built-in streaming apps', 1899.99, 45, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Mechanical Gaming Keyboard', 'Cherry MX switches, RGB per-key lighting, aluminum frame', 159.99, 200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Wireless Gaming Mouse', 'High-precision optical sensor, 16000 DPI, ergonomic design', 89.99, 175, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Smartphone Pro Max', '6.7" AMOLED, 5G, 512GB storage, triple camera system', 1299.99, 80, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tablet 12.9" WiFi', 'Liquid Retina display, M2 chip, 256GB, Apple Pencil support', 1099.99, 60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Smart Watch Series 9', 'Health tracking, GPS, cellular, water resistant, OLED display', 449.99, 120, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Wireless Earbuds Pro', 'Active noise cancellation, spatial audio, 30-hour battery', 249.99, 300, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Portable SSD 2TB', 'USB-C 3.2, up to 1050MB/s read speed, rugged design', 189.99, 95, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Webcam 4K Ultra HD', 'Auto-focus, dual microphones, 90-degree field of view', 129.99, 140, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('USB-C Hub 11-in-1', 'HDMI, USB 3.0, SD card reader, ethernet, 100W charging', 79.99, 220, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bluetooth Speaker Portable', 'Waterproof, 360-degree sound, 20-hour battery, RGB lights', 149.99, 185, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Graphics Card RTX 4070', '12GB GDDR6X, ray tracing, DLSS 3.0, triple fan cooling', 599.99, 35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Monitor 34" Ultrawide', 'WQHD, 144Hz, curved, HDR400, USB-C with 90W charging', 749.99, 55, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Drone with 4K Camera', 'GPS, 30-minute flight time, gimbal stabilization, obstacle avoidance', 899.99, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('E-Reader Paperwhite', '6.8" display, adjustable warm light, waterproof, 16GB storage', 139.99, 210, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Security Camera System', '4-pack wireless, 2K resolution, night vision, motion detection', 299.99, 70, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Power Bank 30000mAh', 'Fast charging, dual USB-C, LED display, portable charger', 69.99, 280, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Soundbar with Subwoofer', 'Dolby Atmos, wireless subwoofer, Bluetooth, HDMI ARC', 399.99, 65, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Home & Kitchen (Products 21-35)
('Robot Vacuum Cleaner', 'Smart mapping, auto-empty station, 3000Pa suction, app control', 549.99, 85, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Air Fryer 8-Quart', 'Digital touchscreen, 12 presets, dishwasher safe, non-stick', 129.99, 160, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Coffee Maker Espresso Machine', 'Built-in grinder, milk frother, programmable, stainless steel', 699.99, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Stand Mixer 6-Quart', '10 speeds, tilt-head design, stainless steel bowl, includes attachments', 349.99, 75, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Instant Pot 8-Quart', 'Pressure cooker, slow cooker, rice cooker, 15-in-1 functions', 119.99, 190, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Blender High-Speed', '1500W motor, self-cleaning, variable speed control, 64oz container', 199.99, 110, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Smart Thermostat', 'WiFi enabled, voice control, energy saving, compatible with Alexa', 249.99, 130, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Memory Foam Mattress Queen', 'Gel-infused, pressure relief, hypoallergenic, 10-inch thickness', 599.99, 45, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Air Purifier HEPA', 'True HEPA filter, covers 900 sq ft, quiet operation, air quality sensor', 279.99, 95, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Towel Set 8-Piece', '100% cotton, quick-dry, soft and absorbent, various colors', 49.99, 250, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cookware Set 15-Piece', 'Non-stick, oven safe, dishwasher safe, includes lids', 189.99, 80, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Electric Kettle 1.7L', 'Fast boil, temperature control, stainless steel, auto shut-off', 59.99, 200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Knife Set 18-Piece', 'High-carbon stainless steel, wooden block, self-sharpening', 149.99, 120, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dining Table Set 5-Piece', 'Modern design, solid wood, includes 4 chairs, easy assembly', 699.99, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('LED Desk Lamp', 'Touch control, USB charging port, adjustable brightness and color', 39.99, 300, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Sports & Outdoors (Products 36-50)
('Treadmill Folding', '3.0HP motor, 12 programs, LCD display, 300lb capacity', 899.99, 35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Yoga Mat Extra Thick', '15mm thick, non-slip surface, eco-friendly TPE, carrying strap', 34.99, 400, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Adjustable Dumbbells Set', '5-52.5 lbs per dumbbell, space-saving, quick adjustment', 449.99, 70, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Camping Tent 6-Person', 'Waterproof, easy setup, ventilation windows, carrying bag included', 249.99, 90, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Mountain Bike 29"', '21-speed, aluminum frame, disc brakes, front suspension', 599.99, 55, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Kayak Inflatable', '2-person, includes paddles and pump, 500lb capacity, storage bag', 399.99, 65, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Swimming Goggles Pro', 'Anti-fog, UV protection, adjustable strap, comfortable seal', 24.99, 500, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Running Shoes Men', 'Breathable mesh, cushioned sole, lightweight, arch support', 89.99, 220, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fitness Tracker Band', 'Heart rate monitor, sleep tracking, waterproof, 7-day battery', 79.99, 280, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hiking Backpack 50L', 'Waterproof, multiple compartments, ergonomic design, rain cover', 119.99, 140, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tennis Racket Professional', 'Graphite frame, 27 inches, pre-strung, carrying case included', 149.99, 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Golf Club Set Complete', '12-piece set, driver, irons, putter, bag included, beginner friendly', 699.99, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Resistance Bands Set', '5 bands, different resistance levels, door anchor, carrying bag', 29.99, 350, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Basketball Official Size', 'Indoor/outdoor, premium composite leather, official weight', 39.99, 200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fishing Rod and Reel Combo', 'Carbon fiber, spinning reel, suitable for freshwater and saltwater', 129.99, 110, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Books & Media (Products 51-60)
('Best Seller Fiction Book', 'Award-winning novel, hardcover, 450 pages, critically acclaimed', 27.99, 500, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cookbook Mediterranean', 'Over 200 recipes, full-color photos, hardcover, diet-friendly', 34.99, 180, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Self-Help Book Bestseller', 'Life-changing advice, paperback, #1 New York Times bestseller', 16.99, 600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Children Picture Book', 'Illustrated, ages 3-7, bedtime stories, award winner', 14.99, 450, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Programming Guide Advanced', 'Complete reference, 800 pages, includes online resources', 59.99, 150, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('History Book World War', 'Detailed account, maps included, hardcover, 600 pages', 39.99, 220, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Art Book Collection', 'Coffee table book, full-color prints, museum quality, hardcover', 89.99, 80, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Science Encyclopedia', 'Illustrated guide, 1000+ pages, comprehensive, reference book', 49.99, 130, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Business Strategy Book', 'Proven methods, case studies, hardcover, MBA recommended', 44.99, 200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Travel Guide Europe', 'Updated edition, maps, photos, insider tips, paperback', 24.99, 300, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Clothing & Accessories (Products 61-75)
('Men Winter Jacket', 'Waterproof, insulated, multiple pockets, hood included', 149.99, 120, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Women Leather Handbag', 'Genuine leather, multiple compartments, adjustable strap', 199.99, 90, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Athletic Shorts Men', 'Quick-dry fabric, zippered pockets, elastic waistband', 29.99, 350, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dress Shirt Men Slim Fit', 'Wrinkle-free, cotton blend, various colors, button-down', 39.99, 280, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Women Yoga Pants', 'High-waist, moisture-wicking, 4-way stretch, phone pocket', 49.99, 400, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sneakers Casual Unisex', 'Canvas upper, rubber sole, comfortable, multiple colors', 69.99, 250, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Winter Scarf Cashmere', 'Soft and warm, 100% cashmere, oversized, unisex', 89.99, 150, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sunglasses Polarized', 'UV400 protection, metal frame, includes case, designer style', 59.99, 200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Leather Belt Men', 'Genuine leather, reversible, adjustable, silver buckle', 44.99, 180, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Backpack School', 'Laptop compartment, water-resistant, padded straps, USB port', 79.99, 220, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Watch Automatic Men', 'Stainless steel, sapphire crystal, water-resistant 100m', 349.99, 75, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Wallet Leather RFID', 'Genuine leather, RFID blocking, slim design, 8 card slots', 34.99, 300, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Baseball Cap Adjustable', 'Cotton twill, adjustable strap, embroidered logo, unisex', 19.99, 450, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Socks Pack 12 Pairs', 'Cotton blend, crew length, cushioned, breathable', 24.99, 500, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tie Silk Men', 'Pure silk, classic pattern, gift box included, 3.5 inches wide', 29.99, 200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Toys & Games (Products 76-85)
('LEGO Building Set', '2000+ pieces, ages 8+, includes instructions, creative building', 149.99, 160, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Remote Control Car', '4WD, rechargeable battery, 30mph speed, off-road capable', 89.99, 140, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Board Game Strategy', 'Ages 10+, 2-6 players, 60-90 minute gameplay, award winner', 49.99, 200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Action Figure Set', 'Superhero collection, 6 figures, articulated, display stand', 79.99, 180, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Puzzle 1000 Pieces', 'Scenic landscape, high-quality cardboard, finished size 27x20 inches', 24.99, 250, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Stuffed Animal Giant', 'Extra large teddy bear, soft and cuddly, 3 feet tall', 69.99, 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Science Kit for Kids', 'STEM learning, 50+ experiments, ages 8-12, educational', 59.99, 130, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dollhouse Wooden', '3 floors, furniture included, opens for easy play, assembly required', 199.99, 60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Playing Cards Premium', 'Casino quality, plastic-coated, 2 decks, storage case', 19.99, 400, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Nerf Blaster Elite', 'Motorized, 100-dart capacity, includes darts, ages 8+', 79.99, 170, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Office & Stationery (Products 86-95)
('Office Chair Ergonomic', 'Lumbar support, adjustable height and armrests, mesh back', 299.99, 80, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Standing Desk Adjustable', 'Electric height adjustment, 48x24 inches, memory presets', 449.99, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Printer All-in-One', 'Print, scan, copy, wireless, duplex printing, ink included', 249.99, 95, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Notebook Set 6-Pack', 'Hardcover, ruled pages, 100 sheets each, elastic closure', 34.99, 300, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Pen Set Luxury', 'Fountain and ballpoint, gift box, premium metal construction', 89.99, 150, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Paper Shredder', 'Cross-cut, 12-sheet capacity, quiet operation, auto-reverse', 79.99, 110, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Desk Organizer Set', '5-piece bamboo set, drawer, pen holder, tray, eco-friendly', 44.99, 200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whiteboard 48x36"', 'Magnetic dry erase, aluminum frame, includes markers and eraser', 129.99, 70, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('File Cabinet 3-Drawer', 'Lockable, steel construction, letter/legal size, anti-tilt', 249.99, 55, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Calculator Scientific', 'Large display, solar powered, 240 functions, protective case', 24.99, 350, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Automotive & Beauty (Products 96-100)
('Car Dash Cam', 'Front and rear cameras, 4K resolution, night vision, GPS', 199.99, 120, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tire Pressure Monitor', 'Wireless, real-time display, 4 external sensors, USB charging', 89.99, 140, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Car Vacuum Cleaner', 'Handheld, cordless, powerful suction, includes attachments', 69.99, 180, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Skincare Set Premium', '5-piece collection, anti-aging, natural ingredients, travel size', 149.99, 160, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hair Dryer Professional', 'Ionic technology, 3 heat settings, cool shot, concentrator nozzle', 119.99, 130, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

